### ISSUE TITLE
PoC of fetching data server- and front-end side

### ISSUE THREAD

**Issue by sectore** [aelve/guide#166]
To fetch data on server- (Node) and front-end (JS) we have to use a library which is supported on both sides. PureScript's [`Network.HTTP.Affjax`](https://pursuit.purescript.org/packages/purescript-affjax/4.0.0/docs/Network.HTTP.Affjax) won't work for this. So let's try it with `isomorphic-fetch`.

**TODOs:**
- [x] FFI for `isomorphic-fetch`
- [x] Example for fetching data of a public API (e.g. Github users)
- [x] Fetch data of `Guide`'s API
