### ISSUE TITLE
Improve `webpack` configs

### ISSUE THREAD

**Issue by sectore** [aelve/guide#167]
Currently `webpack` configurations are based on `pux-starter-app`, which could (and should) be improved:

**TODOs:**
- [ ] Extract a common configuration to be DRY
- [ ] Consider to use one configuration file only (check`react-starter-kit` as an example https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js )
- [ ] Consider to run configurations in parallel using [`npm-run-all`](https://github.com/mysticatea/npm-run-all) to build independently (here is an example https://github.com/ThomasCrevoisier/kfe-front/blob/master/package.json#L10)
